update docs and debian package (initial)

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,2 +1,3 @@
-#!/bin/sh
-setcap cap_net_admin=eip /usr/sbin/lokinet || echo "failed to setcap lokinet"
+#!/bin/sh -e
+setcap cap_net_admin=+eip /usr/sbin/lokinet || echo "failed to setcap lokinet"
+adduser --quiet --system debian-lokinet
